#!/bin/bash
while getopts i:t:l:u:n: option
do
case "${option}"
in
i) UUID=${OPTARG};;
t) TOKEN=${OPTARG};;
l) APP_LOG=${OPTARG};;
u) APP_USER=${OPTARG};;
n) APP_NAME=${OPTARG};;
esac
done

touch $APP_LOG
echo $UUID >> $APP_LOG
echo $TOKEN >> $APP_LOG
echo $APP_LOG >> $APP_LOG
echo $APP_USER >> $APP_LOG
echo $APP_NAME >> $APP_LOG

# get the tarball
# extract it
# make database via api
# get DB name and pwd from api
# import sql using db info
# update wp-config.php with db info

